export type Character = {
  name: string;
  slug: string;
  group: 'main' | 'misc';
  quote: string;
  image: string;
  info: string;
  introduction: string;
  backstory: string;
  credits: string;
};

const placeholder = {
  quote: '[character quote]',
  image: '',
  info: '- age: [add age]\n- race: [add race]\n- technical name: [add technical name]',
  introduction: '[write an introduction here]',
  backstory: '[write the backstory here]',
  credits: '[add name(s)]',
};

export const characters: Character[] = [
  {
    name: 'Axis',
    slug: 'axis',
    group: 'main',
    quote: '"hi. i axis."',
    image: '/media/ocs/axis.png',
    info: '- age: ???\n- race: Geometry\n- technical name: Axis\n- nickname: \'The Beloved\'',
    introduction: 'It\'s... It\'s axis! The one and only! He\'s a little goober who\'s colored both blue and green, with the green being his body, and the blue being his head color! Why is his head blue, you may ask? I have no idea. What I do know is that on the spaceman skin for him, I decided it would be plausible to color his head blue, like he was being seen through blue glass. I just decided to keep the blue and just color his head like that, cause it wasn\'t really like he needed the air anyways. He\'s a shape, silly!',
    backstory: 'After the events of *"The Great Falling"*, where Axis himself was stranded in space for an unremarkable amount of time, he would eventually make his way back to earth, but around a few hundred years later. The year was most likely around **2320**, and the world was drastically different compared to when he was there last. He is considered the original split-form, an originalistic idea generated by researches conducted by praxor!IRL at the time. Speaking of researches, Axis is considered the dumbest of the four, yet he is idealistically the most powerful at base. *The stats on these guys need to be studied, like seriously.*',
    credits: 'praxor, toohi',
  },
  {
    name: 'praxor V1',
    slug: 'praxor-v1',
    group: 'main',
    quote: '"I\'ve got swag, not your dumbass!"',
    image: '/media/ocs/praxor-v1.png',
    info: '- age: 17\n- race: Machine\n- technical name: Praxor\n- nickname: \'The Iconic\'',
    introduction: 'Well, that\'s your guy alright. It\'s **THE** praxor that everyone knows and loves, *as some may say he\'s quite **Iconic***, and he surely is that type of guy. He is considered the most projecting personality among the main group, always showcasing that damn gold chain whenever he can.\n\n As a split-form of Axis, he had taken the swagger out of him and meticulously perfected it and shaped it to his own will, as his soul was encased tightly within the grooves of a mechanical body. Not much else needs to be said about him, really. He\'s already got an unrefined figure, and his clothes pretty much cover it up and make up for it, with his troubling blue sweater, fuckass chain, and carefully chosen pair of pants that he parades.',
    backstory: 'During an augmented experiment into Axis\'s power, THIS version of Praxor was born as a soul during one of the tests, and was quite chaotic before being sealed within the confines of a testing dummy so that destruction wasn\'t caused to the rest of the basement, and house for that matter. *I wasn\'t rich, you know!* Meanwhile, apparently after being sealed inside the dummy, he\'d begin to roam around the basement as a headless creature, until being given a finalized Television screen that wasn\'t just a cruel minute decision made by praxor!IRL, totally. \n\nHis unique ability was spotted right away, as he\'d already personalized just the screen itself to fit him and his personality, practically being *the first sign of his individuality*.',
    credits: 'praxor',
  },
  {
    name: 'praxor V2',
    slug: 'praxor-v2',
    group: 'main',
    quote: '"...and I\'m the bad guy here, huh?"',
    image: '/media/ocs/praxor-v2.png',
    info: '- age: 24\n- race: Machine...?\n- technical name: Praxor\n- nickname: \'The Swagger\'',
    introduction: 'This guy\'s the new *meta* for the praxorians, huh? As a more... older... individual... compared to the rest of the main character cast, this guy\'s like a more refined, actualized version of praxor!V1, but he\'s noticably... colder? Through grit and destruction, he has personally stopped countless forces in order to protect his friends and his own name, maintaining his own senses with just his \'Hammer\'!\n\nAs a second version would suggest, however, this guy isn\'t as sloppily put together as praxor!V1, as he\'s actually built moreso to be a robot, than the "Faker" had ever amounted to. Instead of being a phantom, he\'s got his own form of developed physicality and presence as well, crushing his entire outfit in purple, his own favorite color, despite rocking the blue screen that everyone had known. Wearing a tattered black robe-cape thing, it really shows off the experience and time he\'s put into things, compared to that poser who had come before him.',
    backstory: 'These experiments have to stop, man. Oh wait, it did, cause after that one time when praxor!IRL thought it would be better to make an advanced version of praxor!V1, he had just gone ahead and tried the whole split-form thing again, but instead of it being on Axis, cause he can actually tolerate it, he just tried it on praxor!V1. And whaddya know, praxor!V1 got hospitalized, but half of his soul was somehow evenly torn, and... regenerated? It\'s actually like he had just made a whole copy of himself right then and there, except for some reason, the life from the second soul accelerated as it was no longer in it\'s shell bound by the science of earth. With 3 minutes and 24 seconds on the clock, this guy was sealed inside a prepared robot this time, with his own clothing and everything. \n\nHe *was* supposed to be a new training instructor for a testing facility operated by yours truly, but his screen hadn\'t come on until not one, not two, but three whole days later. Around noon on the third day, he\'d just one day sparked to life without anyone seeing, and had just disappeared for a while. \n\nA whole year later, he\'d come back, bearing the head of a dog as he gently placed it on praxor!IRL\'s doorstep (yuck!), as if it was some sort of trophy? Whatever the reason was, it didn\'t seem like he was any harm, but it did look like the wounded dog (Not the head) had come back to his "owner", scarred but experienced ever-so-suddenly from trials and tribulations later explained in the designated manga (WHAT? WHAT? WHAT?) about him. Hopefully we\'ll be able to figure it out one day, why his cracked screen and torn clothing that had just become his new swagger, had just came about.',
    credits: 'toohi, praxor',
  },
  {
    name: 'praxor (IRL)',
    slug: 'praxor-irl',
    group: 'main',
    quote: '"It\'s you."',
    image: '/media/ocs/praxor-irl.png',
    info: '- age: 18 (as of writing this)\n- race: Human\n- technical name: \'Alex\'\n- nickname: \'The Sweetheart\', \'The Truth\'',
    introduction: 'Well, I can\'t really say much, it\'s just me. I may have created my characters, but I\'d like them to be personally stronger than myself, as it\'s nice to watch a superhero rather than being one. It must be *exhausting* to be that guy!',
    backstory: '## No. Thank you.\n\nMaybe just get to know *me*, instead of reading the docs.',
    credits: 'praxor. Duh. Also my mom too, probably.',
  },
  {
    name: 'Purnid ★',
    slug: 'purnid',
    group: 'misc',
    ...placeholder,
  },
  {
    name: 'Mr. Red',
    slug: 'mr-red',
    group: 'misc',
    ...placeholder,
  },
  {
    name: 'The Praxor Cat(tm)',
    slug: 'the-praxor-cat',
    group: 'misc',
    ...placeholder,
  },
  {
    name: 'Pubbly',
    slug: 'pubbly',
    group: 'misc',
    ...placeholder,
  },
  {
    name: 'High-Intelligence Business Noob',
    slug: 'high-intelligence-business-noob',
    group: 'misc',
    ...placeholder,
  },
  {
    name: 'Mr. Black',
    slug: 'mr-black',
    group: 'misc',
    ...placeholder,
  },
  {
    name: 'Curse',
    slug: 'curse',
    group: 'misc',
    ...placeholder,
  },
  {
    name: 'Prophet',
    slug: 'prophet',
    group: 'misc',
    ...placeholder,
  },
  {
    name: 'Detective White',
    slug: 'detective-white',
    group: 'misc',
    ...placeholder,
  },
];

export const mainCharacters = characters.filter((character) => character.group === 'main');
export const miscCharacters = characters.filter((character) => character.group === 'misc');
